FROM gkutiel/node-android

# Install app dependencies
COPY package*.json ./

# RUN npm install
RUN npm ci --only=production

# Bundle app source
RUN mkdir build
COPY png png
COPY templates templates
COPY mykey.keystore .

